### ISSUE TITLE
cronSTTJobChecker - updateTranscription() is trying to update with undefined

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#85]
**Describe the bug**

Separate issue:
```
 cronSTTJobChecker

Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "dataOrField" is not a valid Firestore value. Cannot use "undefined" as a Firestore value (found in field "payload").
    at WriteBatch.update (/srv/node_modules/@google-cloud/firestore/build/src/write-batch.js:360:23)
    at DocumentReference.update (/srv/node_modules/@google-cloud/firestore/build/src/reference.js:377:14)
    at updateTranscription (/srv/sttChecker/index.js:93:16)
    at validJobs.forEach (/srv/sttChecker/index.js:147:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)


```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by emettely** [comment]
Requires deployment
